// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-bookings.ts
import { createClient } from "npm:@supabase/supabase-js@^2.107.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_bookings_default = defineTool({
  name: "list_bookings",
  title: "List bookings",
  description: "List Trenches Records studio bookings. Filter by studio, status, and date range. Returns up to `limit` rows ordered by date ascending.",
  inputSchema: {
    studio: z.enum(["piccolo", "ssg", "videomaker"]).nullable().describe("Filter by studio/resource."),
    status: z.enum(["pending", "confirmed", "cancelled"]).nullable().describe("Filter by booking status."),
    from_date: z.string().nullable().describe("Inclusive start date YYYY-MM-DD."),
    to_date: z.string().nullable().describe("Inclusive end date YYYY-MM-DD."),
    limit: z.number().int().min(1).max(200).nullable().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("bookings").select(
      "id, studio, date, start_time, end_time, status, deposit_paid, final_paid, total, email, videomaker, videomaker_days, vfx_ai_seconds, created_at"
    ).order("date", { ascending: true }).order("start_time", { ascending: true }).limit(input.limit ?? 50);
    if (input.studio) query = query.eq("studio", input.studio);
    if (input.status) query = query.eq("status", input.status);
    if (input.from_date) query = query.gte("date", input.from_date);
    if (input.to_date) query = query.lte("date", input.to_date);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-booking.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.107.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_booking_default = defineTool2({
  name: "get_booking",
  title: "Get booking",
  description: "Fetch a single booking by id with full details.",
  inputSchema: {
    booking_id: z2.string().uuid().describe("Booking UUID.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ booking_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("bookings").select("*").eq("id", booking_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { booking: data }
    };
  }
});

// src/lib/mcp/tools/list-studio-blocks.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.107.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_studio_blocks_default = defineTool3({
  name: "list_studio_blocks",
  title: "List studio blocks",
  description: "List admin-created unavailability blocks (holidays, maintenance, etc.) per studio.",
  inputSchema: {
    studio: z3.enum(["piccolo", "ssg", "videomaker"]).nullable().describe("Filter by studio/resource.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ studio }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser3(ctx).from("studio_blocks").select("id, studio, start_date, end_date, reason, created_at").order("start_date", { ascending: true });
    if (studio) q = q.eq("studio", studio);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { blocks: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mehouzpbqyfsbuwprtzi";
var mcp_default = defineMcp({
  name: "trenches-records-mcp",
  title: "Trenches Records",
  version: "0.1.0",
  instructions: "Tools to inspect Trenches Records studio bookings and unavailability blocks. Callers authenticate as an app user and RLS scopes what they can read.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_bookings_default, get_booking_default, list_studio_blocks_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
